// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drafts.sql

package db

import (
	"context"
	"database/sql"
)

const listDraftPicksByLeague = `-- name: ListDraftPicksByLeague :many
SELECT id, league_id, draft_id, team_id, player_id, overall_pick, round_num, round_pick, draft_slot, picked_by, keeper_status, created_at FROM drafts
WHERE league_id = $1
ORDER BY overall_pick ASC
`

func (q *Queries) ListDraftPicksByLeague(ctx context.Context, leagueID int64) ([]Draft, error) {
	rows, err := q.db.QueryContext(ctx, listDraftPicksByLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Draft
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.DraftID,
			&i.TeamID,
			&i.PlayerID,
			&i.OverallPick,
			&i.RoundNum,
			&i.RoundPick,
			&i.DraftSlot,
			&i.PickedBy,
			&i.KeeperStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDraftPick = `-- name: UpsertDraftPick :one
INSERT INTO drafts (
    league_id,
    draft_id,
    team_id,
    player_id,
    overall_pick,
    round_num,
    round_pick,
    draft_slot,
    picked_by,
    keeper_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (draft_id, overall_pick) DO UPDATE SET
    team_id = EXCLUDED.team_id,
    player_id = EXCLUDED.player_id,
    round_num = EXCLUDED.round_num,
    round_pick = EXCLUDED.round_pick,
    draft_slot = EXCLUDED.draft_slot,
    picked_by = EXCLUDED.picked_by,
    keeper_status = EXCLUDED.keeper_status
RETURNING id, league_id, draft_id, team_id, player_id, overall_pick, round_num, round_pick, draft_slot, picked_by, keeper_status, created_at
`

type UpsertDraftPickParams struct {
	LeagueID     int64          `json:"league_id"`
	DraftID      string         `json:"draft_id"`
	TeamID       int64          `json:"team_id"`
	PlayerID     int64          `json:"player_id"`
	OverallPick  int32          `json:"overall_pick"`
	RoundNum     int32          `json:"round_num"`
	RoundPick    int32          `json:"round_pick"`
	DraftSlot    sql.NullInt32  `json:"draft_slot"`
	PickedBy     sql.NullString `json:"picked_by"`
	KeeperStatus bool           `json:"keeper_status"`
}

func (q *Queries) UpsertDraftPick(ctx context.Context, arg UpsertDraftPickParams) (Draft, error) {
	row := q.db.QueryRowContext(ctx, upsertDraftPick,
		arg.LeagueID,
		arg.DraftID,
		arg.TeamID,
		arg.PlayerID,
		arg.OverallPick,
		arg.RoundNum,
		arg.RoundPick,
		arg.DraftSlot,
		arg.PickedBy,
		arg.KeeperStatus,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.DraftID,
		&i.TeamID,
		&i.PlayerID,
		&i.OverallPick,
		&i.RoundNum,
		&i.RoundPick,
		&i.DraftSlot,
		&i.PickedBy,
		&i.KeeperStatus,
		&i.CreatedAt,
	)
	return i, err
}
