// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matchups.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const listMatchupsByLeague = `-- name: ListMatchupsByLeague :many
SELECT id, league_id, week, matchup_id, roster_id, opponent_roster_id, points, custom_points, is_playoff, matchup_type, starters, players FROM matchups
WHERE league_id = $1
ORDER BY week ASC, matchup_id ASC, roster_id ASC
`

func (q *Queries) ListMatchupsByLeague(ctx context.Context, leagueID int64) ([]Matchup, error) {
	rows, err := q.db.QueryContext(ctx, listMatchupsByLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Matchup
	for rows.Next() {
		var i Matchup
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.Week,
			&i.MatchupID,
			&i.RosterID,
			&i.OpponentRosterID,
			&i.Points,
			&i.CustomPoints,
			&i.IsPlayoff,
			&i.MatchupType,
			&i.Starters,
			&i.Players,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMatchup = `-- name: UpsertMatchup :one
INSERT INTO matchups (
    league_id,
    week,
    matchup_id,
    roster_id,
    opponent_roster_id,
    points,
    custom_points,
    is_playoff,
    matchup_type,
    starters,
    players
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (league_id, week, matchup_id, roster_id) DO UPDATE SET
    opponent_roster_id = EXCLUDED.opponent_roster_id,
    points = EXCLUDED.points,
    custom_points = EXCLUDED.custom_points,
    is_playoff = EXCLUDED.is_playoff,
    matchup_type = EXCLUDED.matchup_type,
    starters = EXCLUDED.starters,
    players = EXCLUDED.players
RETURNING id, league_id, week, matchup_id, roster_id, opponent_roster_id, points, custom_points, is_playoff, matchup_type, starters, players
`

type UpsertMatchupParams struct {
	LeagueID         int64           `json:"league_id"`
	Week             int32           `json:"week"`
	MatchupID        int32           `json:"matchup_id"`
	RosterID         int32           `json:"roster_id"`
	OpponentRosterID sql.NullInt32   `json:"opponent_roster_id"`
	Points           string          `json:"points"`
	CustomPoints     sql.NullString  `json:"custom_points"`
	IsPlayoff        bool            `json:"is_playoff"`
	MatchupType      string          `json:"matchup_type"`
	Starters         json.RawMessage `json:"starters"`
	Players          json.RawMessage `json:"players"`
}

func (q *Queries) UpsertMatchup(ctx context.Context, arg UpsertMatchupParams) (Matchup, error) {
	row := q.db.QueryRowContext(ctx, upsertMatchup,
		arg.LeagueID,
		arg.Week,
		arg.MatchupID,
		arg.RosterID,
		arg.OpponentRosterID,
		arg.Points,
		arg.CustomPoints,
		arg.IsPlayoff,
		arg.MatchupType,
		arg.Starters,
		arg.Players,
	)
	var i Matchup
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Week,
		&i.MatchupID,
		&i.RosterID,
		&i.OpponentRosterID,
		&i.Points,
		&i.CustomPoints,
		&i.IsPlayoff,
		&i.MatchupType,
		&i.Starters,
		&i.Players,
	)
	return i, err
}
