// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Draft struct {
	ID           int64          `json:"id"`
	LeagueID     int64          `json:"league_id"`
	DraftID      string         `json:"draft_id"`
	TeamID       int64          `json:"team_id"`
	PlayerID     int64          `json:"player_id"`
	OverallPick  int32          `json:"overall_pick"`
	RoundNum     int32          `json:"round_num"`
	RoundPick    int32          `json:"round_pick"`
	DraftSlot    sql.NullInt32  `json:"draft_slot"`
	PickedBy     sql.NullString `json:"picked_by"`
	KeeperStatus bool           `json:"keeper_status"`
	CreatedAt    time.Time      `json:"created_at"`
}

type League struct {
	ID              int64           `json:"id"`
	SleeperLeagueID string          `json:"sleeper_league_id"`
	Season          int32           `json:"season"`
	Name            string          `json:"name"`
	Status          string          `json:"status"`
	Sport           string          `json:"sport"`
	TotalRosters    int32           `json:"total_rosters"`
	DraftID         sql.NullString  `json:"draft_id"`
	Avatar          sql.NullString  `json:"avatar"`
	RosterPositions json.RawMessage `json:"roster_positions"`
	ScoringSettings json.RawMessage `json:"scoring_settings"`
	LeagueSettings  json.RawMessage `json:"league_settings"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type Matchup struct {
	ID               int64           `json:"id"`
	LeagueID         int64           `json:"league_id"`
	Week             int32           `json:"week"`
	MatchupID        int32           `json:"matchup_id"`
	RosterID         int32           `json:"roster_id"`
	OpponentRosterID sql.NullInt32   `json:"opponent_roster_id"`
	Points           string          `json:"points"`
	CustomPoints     sql.NullString  `json:"custom_points"`
	IsPlayoff        bool            `json:"is_playoff"`
	MatchupType      string          `json:"matchup_type"`
	Starters         json.RawMessage `json:"starters"`
	Players          json.RawMessage `json:"players"`
}

type Player struct {
	ID               int64           `json:"id"`
	SleeperID        string          `json:"sleeper_id"`
	EspnID           sql.NullString  `json:"espn_id"`
	Name             string          `json:"name"`
	FirstName        sql.NullString  `json:"first_name"`
	LastName         sql.NullString  `json:"last_name"`
	Position         sql.NullString  `json:"position"`
	Team             sql.NullString  `json:"team"`
	Status           sql.NullString  `json:"status"`
	FantasyPositions json.RawMessage `json:"fantasy_positions"`
	Age              sql.NullInt32   `json:"age"`
}

type Roster struct {
	ID         int64  `json:"id"`
	LeagueID   int64  `json:"league_id"`
	Week       int32  `json:"week"`
	RosterID   int32  `json:"roster_id"`
	PlayerID   int64  `json:"player_id"`
	RosterSlot string `json:"roster_slot"`
	IsStarter  bool   `json:"is_starter"`
}

type Team struct {
	ID               int64          `json:"id"`
	LeagueID         int64          `json:"league_id"`
	RosterID         int32          `json:"roster_id"`
	OwnerID          string         `json:"owner_id"`
	UserID           sql.NullString `json:"user_id"`
	DisplayName      sql.NullString `json:"display_name"`
	Username         sql.NullString `json:"username"`
	TeamName         string         `json:"team_name"`
	Avatar           sql.NullString `json:"avatar"`
	Wins             int32          `json:"wins"`
	Losses           int32          `json:"losses"`
	Ties             int32          `json:"ties"`
	PointsFor        string         `json:"points_for"`
	PointsAgainst    string         `json:"points_against"`
	WaiverPosition   int32          `json:"waiver_position"`
	WaiverBudgetUsed int32          `json:"waiver_budget_used"`
	TotalMoves       int32          `json:"total_moves"`
	StreakType       string         `json:"streak_type"`
	StreakLength     int32          `json:"streak_length"`
	Standing         int32          `json:"standing"`
	FinalStanding    int32          `json:"final_standing"`
}
