// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getPlayerByESPNID = `-- name: GetPlayerByESPNID :one
SELECT id, sleeper_id, espn_id, name, first_name, last_name, position, team, status, fantasy_positions, age FROM players
WHERE espn_id = $1
`

func (q *Queries) GetPlayerByESPNID(ctx context.Context, espnID sql.NullString) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByESPNID, espnID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.SleeperID,
		&i.EspnID,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.Team,
		&i.Status,
		&i.FantasyPositions,
		&i.Age,
	)
	return i, err
}

const getPlayerBySleeperID = `-- name: GetPlayerBySleeperID :one
SELECT id, sleeper_id, espn_id, name, first_name, last_name, position, team, status, fantasy_positions, age FROM players
WHERE sleeper_id = $1
`

func (q *Queries) GetPlayerBySleeperID(ctx context.Context, sleeperID string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerBySleeperID, sleeperID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.SleeperID,
		&i.EspnID,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.Team,
		&i.Status,
		&i.FantasyPositions,
		&i.Age,
	)
	return i, err
}

const upsertPlayer = `-- name: UpsertPlayer :one
INSERT INTO players (
    sleeper_id,
    espn_id,
    name,
    first_name,
    last_name,
    position,
    team,
    status,
    fantasy_positions,
    age
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (sleeper_id) DO UPDATE SET
    espn_id = EXCLUDED.espn_id,
    name = EXCLUDED.name,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    position = EXCLUDED.position,
    team = EXCLUDED.team,
    status = EXCLUDED.status,
    fantasy_positions = EXCLUDED.fantasy_positions,
    age = EXCLUDED.age
RETURNING id, sleeper_id, espn_id, name, first_name, last_name, position, team, status, fantasy_positions, age
`

type UpsertPlayerParams struct {
	SleeperID        string          `json:"sleeper_id"`
	EspnID           sql.NullString  `json:"espn_id"`
	Name             string          `json:"name"`
	FirstName        sql.NullString  `json:"first_name"`
	LastName         sql.NullString  `json:"last_name"`
	Position         sql.NullString  `json:"position"`
	Team             sql.NullString  `json:"team"`
	Status           sql.NullString  `json:"status"`
	FantasyPositions json.RawMessage `json:"fantasy_positions"`
	Age              sql.NullInt32   `json:"age"`
}

func (q *Queries) UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, upsertPlayer,
		arg.SleeperID,
		arg.EspnID,
		arg.Name,
		arg.FirstName,
		arg.LastName,
		arg.Position,
		arg.Team,
		arg.Status,
		arg.FantasyPositions,
		arg.Age,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.SleeperID,
		&i.EspnID,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.Team,
		&i.Status,
		&i.FantasyPositions,
		&i.Age,
	)
	return i, err
}
