// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playoff_brackets.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const listPlayoffBracketMatchupsByLeague = `-- name: ListPlayoffBracketMatchupsByLeague :many
SELECT id, league_id, bracket_type, round_num, matchup_id, placement, slot1_roster_id, slot2_roster_id, slot1_source_matchup_id, slot1_source_result, slot2_source_matchup_id, slot2_source_result, winner_roster_id, loser_roster_id, raw_payload FROM playoff_bracket_matchups
WHERE league_id = $1
ORDER BY bracket_type ASC, round_num ASC, matchup_id ASC
`

func (q *Queries) ListPlayoffBracketMatchupsByLeague(ctx context.Context, leagueID int64) ([]PlayoffBracketMatchup, error) {
	rows, err := q.db.QueryContext(ctx, listPlayoffBracketMatchupsByLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayoffBracketMatchup
	for rows.Next() {
		var i PlayoffBracketMatchup
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.BracketType,
			&i.RoundNum,
			&i.MatchupID,
			&i.Placement,
			&i.Slot1RosterID,
			&i.Slot2RosterID,
			&i.Slot1SourceMatchupID,
			&i.Slot1SourceResult,
			&i.Slot2SourceMatchupID,
			&i.Slot2SourceResult,
			&i.WinnerRosterID,
			&i.LoserRosterID,
			&i.RawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayoffBracketMatchup = `-- name: UpsertPlayoffBracketMatchup :one
INSERT INTO playoff_bracket_matchups (
    league_id,
    bracket_type,
    round_num,
    matchup_id,
    placement,
    slot1_roster_id,
    slot2_roster_id,
    slot1_source_matchup_id,
    slot1_source_result,
    slot2_source_matchup_id,
    slot2_source_result,
    winner_roster_id,
    loser_roster_id,
    raw_payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (league_id, bracket_type, matchup_id) DO UPDATE SET
    round_num = EXCLUDED.round_num,
    placement = EXCLUDED.placement,
    slot1_roster_id = EXCLUDED.slot1_roster_id,
    slot2_roster_id = EXCLUDED.slot2_roster_id,
    slot1_source_matchup_id = EXCLUDED.slot1_source_matchup_id,
    slot1_source_result = EXCLUDED.slot1_source_result,
    slot2_source_matchup_id = EXCLUDED.slot2_source_matchup_id,
    slot2_source_result = EXCLUDED.slot2_source_result,
    winner_roster_id = EXCLUDED.winner_roster_id,
    loser_roster_id = EXCLUDED.loser_roster_id,
    raw_payload = EXCLUDED.raw_payload
RETURNING id, league_id, bracket_type, round_num, matchup_id, placement, slot1_roster_id, slot2_roster_id, slot1_source_matchup_id, slot1_source_result, slot2_source_matchup_id, slot2_source_result, winner_roster_id, loser_roster_id, raw_payload
`

type UpsertPlayoffBracketMatchupParams struct {
	LeagueID             int64           `json:"league_id"`
	BracketType          string          `json:"bracket_type"`
	RoundNum             int32           `json:"round_num"`
	MatchupID            int32           `json:"matchup_id"`
	Placement            sql.NullInt32   `json:"placement"`
	Slot1RosterID        sql.NullInt32   `json:"slot1_roster_id"`
	Slot2RosterID        sql.NullInt32   `json:"slot2_roster_id"`
	Slot1SourceMatchupID sql.NullInt32   `json:"slot1_source_matchup_id"`
	Slot1SourceResult    sql.NullString  `json:"slot1_source_result"`
	Slot2SourceMatchupID sql.NullInt32   `json:"slot2_source_matchup_id"`
	Slot2SourceResult    sql.NullString  `json:"slot2_source_result"`
	WinnerRosterID       sql.NullInt32   `json:"winner_roster_id"`
	LoserRosterID        sql.NullInt32   `json:"loser_roster_id"`
	RawPayload           json.RawMessage `json:"raw_payload"`
}

func (q *Queries) UpsertPlayoffBracketMatchup(ctx context.Context, arg UpsertPlayoffBracketMatchupParams) (PlayoffBracketMatchup, error) {
	row := q.db.QueryRowContext(ctx, upsertPlayoffBracketMatchup,
		arg.LeagueID,
		arg.BracketType,
		arg.RoundNum,
		arg.MatchupID,
		arg.Placement,
		arg.Slot1RosterID,
		arg.Slot2RosterID,
		arg.Slot1SourceMatchupID,
		arg.Slot1SourceResult,
		arg.Slot2SourceMatchupID,
		arg.Slot2SourceResult,
		arg.WinnerRosterID,
		arg.LoserRosterID,
		arg.RawPayload,
	)
	var i PlayoffBracketMatchup
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.BracketType,
		&i.RoundNum,
		&i.MatchupID,
		&i.Placement,
		&i.Slot1RosterID,
		&i.Slot2RosterID,
		&i.Slot1SourceMatchupID,
		&i.Slot1SourceResult,
		&i.Slot2SourceMatchupID,
		&i.Slot2SourceResult,
		&i.WinnerRosterID,
		&i.LoserRosterID,
		&i.RawPayload,
	)
	return i, err
}
