// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"
)

const listLeagueReports = `-- name: ListLeagueReports :many
SELECT
    l.id AS league_id,
    l.season,
    l.name,
    l.total_rosters,
    (
        SELECT count(*)
        FROM teams t
        WHERE t.league_id = l.id
    ) AS team_count,
    (
        SELECT count(*)
        FROM drafts d
        WHERE d.league_id = l.id
    ) AS draft_pick_count,
    coalesce((
        SELECT min(m.week)
        FROM matchups m
        WHERE m.league_id = l.id
    ), 0)::integer AS matchup_min_week,
    coalesce((
        SELECT max(m.week)
        FROM matchups m
        WHERE m.league_id = l.id
    ), 0)::integer AS matchup_max_week,
    (
        SELECT count(*)
        FROM matchups m
        WHERE m.league_id = l.id
    ) AS matchup_entry_count,
    (
        SELECT count(*)
        FROM rosters r
        WHERE r.league_id = l.id
          AND r.week = 0
    ) AS current_roster_entry_count,
    (
        SELECT count(*)
        FROM rosters r
        WHERE r.league_id = l.id
          AND r.week > 0
    ) AS weekly_roster_entry_count,
    (
        SELECT count(*)
        FROM playoff_bracket_matchups pbm
        WHERE pbm.league_id = l.id
    ) AS playoff_bracket_matchup_count,
    coalesce((
        SELECT t.team_name
        FROM teams t
        WHERE t.league_id = l.id
          AND t.final_standing = 1
        ORDER BY t.roster_id ASC
        LIMIT 1
    ), '')::text AS champion_team_name,
    coalesce((
        SELECT t.team_name
        FROM teams t
        WHERE t.league_id = l.id
          AND t.final_standing = 2
        ORDER BY t.roster_id ASC
        LIMIT 1
    ), '')::text AS runner_up_team_name,
    (
        SELECT count(*)
        FROM teams t
        WHERE t.league_id = l.id
          AND t.final_standing = 0
    ) AS missing_final_standing_count,
    (
        SELECT count(*)
        FROM (
            SELECT t.final_standing
            FROM teams t
            WHERE t.league_id = l.id
              AND t.final_standing > 0
            GROUP BY t.final_standing
            HAVING count(*) > 1
        ) duplicate_standings
    ) AS duplicate_final_standing_count
FROM leagues l
ORDER BY l.season ASC, l.name ASC
`

type ListLeagueReportsRow struct {
	LeagueID                    int64  `json:"league_id"`
	Season                      int32  `json:"season"`
	Name                        string `json:"name"`
	TotalRosters                int32  `json:"total_rosters"`
	TeamCount                   int64  `json:"team_count"`
	DraftPickCount              int64  `json:"draft_pick_count"`
	MatchupMinWeek              int32  `json:"matchup_min_week"`
	MatchupMaxWeek              int32  `json:"matchup_max_week"`
	MatchupEntryCount           int64  `json:"matchup_entry_count"`
	CurrentRosterEntryCount     int64  `json:"current_roster_entry_count"`
	WeeklyRosterEntryCount      int64  `json:"weekly_roster_entry_count"`
	PlayoffBracketMatchupCount  int64  `json:"playoff_bracket_matchup_count"`
	ChampionTeamName            string `json:"champion_team_name"`
	RunnerUpTeamName            string `json:"runner_up_team_name"`
	MissingFinalStandingCount   int64  `json:"missing_final_standing_count"`
	DuplicateFinalStandingCount int64  `json:"duplicate_final_standing_count"`
}

func (q *Queries) ListLeagueReports(ctx context.Context) ([]ListLeagueReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLeagueReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeagueReportsRow
	for rows.Next() {
		var i ListLeagueReportsRow
		if err := rows.Scan(
			&i.LeagueID,
			&i.Season,
			&i.Name,
			&i.TotalRosters,
			&i.TeamCount,
			&i.DraftPickCount,
			&i.MatchupMinWeek,
			&i.MatchupMaxWeek,
			&i.MatchupEntryCount,
			&i.CurrentRosterEntryCount,
			&i.WeeklyRosterEntryCount,
			&i.PlayoffBracketMatchupCount,
			&i.ChampionTeamName,
			&i.RunnerUpTeamName,
			&i.MissingFinalStandingCount,
			&i.DuplicateFinalStandingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
