// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rosters.sql

package db

import (
	"context"
)

const listRosterEntriesByLeague = `-- name: ListRosterEntriesByLeague :many
SELECT id, league_id, week, roster_id, player_id, roster_slot, is_starter FROM rosters
WHERE league_id = $1
ORDER BY week ASC, roster_id ASC, player_id ASC
`

func (q *Queries) ListRosterEntriesByLeague(ctx context.Context, leagueID int64) ([]Roster, error) {
	rows, err := q.db.QueryContext(ctx, listRosterEntriesByLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Roster
	for rows.Next() {
		var i Roster
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.Week,
			&i.RosterID,
			&i.PlayerID,
			&i.RosterSlot,
			&i.IsStarter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRosterEntry = `-- name: UpsertRosterEntry :one
INSERT INTO rosters (
    league_id,
    week,
    roster_id,
    player_id,
    roster_slot,
    is_starter
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (league_id, week, roster_id, player_id) DO UPDATE SET
    roster_slot = EXCLUDED.roster_slot,
    is_starter = EXCLUDED.is_starter
RETURNING id, league_id, week, roster_id, player_id, roster_slot, is_starter
`

type UpsertRosterEntryParams struct {
	LeagueID   int64  `json:"league_id"`
	Week       int32  `json:"week"`
	RosterID   int32  `json:"roster_id"`
	PlayerID   int64  `json:"player_id"`
	RosterSlot string `json:"roster_slot"`
	IsStarter  bool   `json:"is_starter"`
}

func (q *Queries) UpsertRosterEntry(ctx context.Context, arg UpsertRosterEntryParams) (Roster, error) {
	row := q.db.QueryRowContext(ctx, upsertRosterEntry,
		arg.LeagueID,
		arg.Week,
		arg.RosterID,
		arg.PlayerID,
		arg.RosterSlot,
		arg.IsStarter,
	)
	var i Roster
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Week,
		&i.RosterID,
		&i.PlayerID,
		&i.RosterSlot,
		&i.IsStarter,
	)
	return i, err
}
