// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"
	"database/sql"
)

const getTeamByLeagueAndRoster = `-- name: GetTeamByLeagueAndRoster :one
SELECT id, league_id, roster_id, owner_id, user_id, display_name, username, team_name, avatar, wins, losses, ties, points_for, points_against, waiver_position, waiver_budget_used, total_moves, streak_type, streak_length, standing, final_standing FROM teams
WHERE league_id = $1
  AND roster_id = $2
`

type GetTeamByLeagueAndRosterParams struct {
	LeagueID int64 `json:"league_id"`
	RosterID int32 `json:"roster_id"`
}

func (q *Queries) GetTeamByLeagueAndRoster(ctx context.Context, arg GetTeamByLeagueAndRosterParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByLeagueAndRoster, arg.LeagueID, arg.RosterID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.RosterID,
		&i.OwnerID,
		&i.UserID,
		&i.DisplayName,
		&i.Username,
		&i.TeamName,
		&i.Avatar,
		&i.Wins,
		&i.Losses,
		&i.Ties,
		&i.PointsFor,
		&i.PointsAgainst,
		&i.WaiverPosition,
		&i.WaiverBudgetUsed,
		&i.TotalMoves,
		&i.StreakType,
		&i.StreakLength,
		&i.Standing,
		&i.FinalStanding,
	)
	return i, err
}

const listTeamsByLeague = `-- name: ListTeamsByLeague :many
SELECT id, league_id, roster_id, owner_id, user_id, display_name, username, team_name, avatar, wins, losses, ties, points_for, points_against, waiver_position, waiver_budget_used, total_moves, streak_type, streak_length, standing, final_standing FROM teams
WHERE league_id = $1
ORDER BY final_standing ASC, roster_id ASC
`

func (q *Queries) ListTeamsByLeague(ctx context.Context, leagueID int64) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsByLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.RosterID,
			&i.OwnerID,
			&i.UserID,
			&i.DisplayName,
			&i.Username,
			&i.TeamName,
			&i.Avatar,
			&i.Wins,
			&i.Losses,
			&i.Ties,
			&i.PointsFor,
			&i.PointsAgainst,
			&i.WaiverPosition,
			&i.WaiverBudgetUsed,
			&i.TotalMoves,
			&i.StreakType,
			&i.StreakLength,
			&i.Standing,
			&i.FinalStanding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetLeagueFinalStandings = `-- name: ResetLeagueFinalStandings :exec
UPDATE teams
SET final_standing = standing
WHERE league_id = $1
`

func (q *Queries) ResetLeagueFinalStandings(ctx context.Context, leagueID int64) error {
	_, err := q.db.ExecContext(ctx, resetLeagueFinalStandings, leagueID)
	return err
}

const updateTeamFinalStanding = `-- name: UpdateTeamFinalStanding :exec
UPDATE teams
SET final_standing = $3
WHERE league_id = $1
  AND roster_id = $2
`

type UpdateTeamFinalStandingParams struct {
	LeagueID      int64 `json:"league_id"`
	RosterID      int32 `json:"roster_id"`
	FinalStanding int32 `json:"final_standing"`
}

func (q *Queries) UpdateTeamFinalStanding(ctx context.Context, arg UpdateTeamFinalStandingParams) error {
	_, err := q.db.ExecContext(ctx, updateTeamFinalStanding, arg.LeagueID, arg.RosterID, arg.FinalStanding)
	return err
}

const upsertTeam = `-- name: UpsertTeam :one
INSERT INTO teams (
    league_id,
    roster_id,
    owner_id,
    user_id,
    display_name,
    username,
    team_name,
    avatar,
    wins,
    losses,
    ties,
    points_for,
    points_against,
    waiver_position,
    waiver_budget_used,
    total_moves,
    streak_type,
    streak_length,
    standing,
    final_standing
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
ON CONFLICT (league_id, roster_id) DO UPDATE SET
    owner_id = EXCLUDED.owner_id,
    user_id = EXCLUDED.user_id,
    display_name = EXCLUDED.display_name,
    username = EXCLUDED.username,
    team_name = EXCLUDED.team_name,
    avatar = EXCLUDED.avatar,
    wins = EXCLUDED.wins,
    losses = EXCLUDED.losses,
    ties = EXCLUDED.ties,
    points_for = EXCLUDED.points_for,
    points_against = EXCLUDED.points_against,
    waiver_position = EXCLUDED.waiver_position,
    waiver_budget_used = EXCLUDED.waiver_budget_used,
    total_moves = EXCLUDED.total_moves,
    streak_type = EXCLUDED.streak_type,
    streak_length = EXCLUDED.streak_length,
    standing = EXCLUDED.standing
RETURNING id, league_id, roster_id, owner_id, user_id, display_name, username, team_name, avatar, wins, losses, ties, points_for, points_against, waiver_position, waiver_budget_used, total_moves, streak_type, streak_length, standing, final_standing
`

type UpsertTeamParams struct {
	LeagueID         int64          `json:"league_id"`
	RosterID         int32          `json:"roster_id"`
	OwnerID          string         `json:"owner_id"`
	UserID           sql.NullString `json:"user_id"`
	DisplayName      sql.NullString `json:"display_name"`
	Username         sql.NullString `json:"username"`
	TeamName         string         `json:"team_name"`
	Avatar           sql.NullString `json:"avatar"`
	Wins             int32          `json:"wins"`
	Losses           int32          `json:"losses"`
	Ties             int32          `json:"ties"`
	PointsFor        string         `json:"points_for"`
	PointsAgainst    string         `json:"points_against"`
	WaiverPosition   int32          `json:"waiver_position"`
	WaiverBudgetUsed int32          `json:"waiver_budget_used"`
	TotalMoves       int32          `json:"total_moves"`
	StreakType       string         `json:"streak_type"`
	StreakLength     int32          `json:"streak_length"`
	Standing         int32          `json:"standing"`
	FinalStanding    int32          `json:"final_standing"`
}

func (q *Queries) UpsertTeam(ctx context.Context, arg UpsertTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, upsertTeam,
		arg.LeagueID,
		arg.RosterID,
		arg.OwnerID,
		arg.UserID,
		arg.DisplayName,
		arg.Username,
		arg.TeamName,
		arg.Avatar,
		arg.Wins,
		arg.Losses,
		arg.Ties,
		arg.PointsFor,
		arg.PointsAgainst,
		arg.WaiverPosition,
		arg.WaiverBudgetUsed,
		arg.TotalMoves,
		arg.StreakType,
		arg.StreakLength,
		arg.Standing,
		arg.FinalStanding,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.RosterID,
		&i.OwnerID,
		&i.UserID,
		&i.DisplayName,
		&i.Username,
		&i.TeamName,
		&i.Avatar,
		&i.Wins,
		&i.Losses,
		&i.Ties,
		&i.PointsFor,
		&i.PointsAgainst,
		&i.WaiverPosition,
		&i.WaiverBudgetUsed,
		&i.TotalMoves,
		&i.StreakType,
		&i.StreakLength,
		&i.Standing,
		&i.FinalStanding,
	)
	return i, err
}
